name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3 
      - name: Run-Gradle
        run: ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code  
          path: .
    Docker-image:
         runs-on: ubuntu-latest
         needs: [my-job]
         permissions:
          packages: write
        steps:
        - name: Download code
        - uses: actions/download-artifact@v3
          with:
            name: code
            path: .
        - name: Build Docker
          run: cmod +x ci/build-docker.sh && ci/build-docker.sh
        - name: push docker
          run: cmod +x ci/push-docker.sh && ci/push-docker.sh